[package]
name = "feeds"
version = "0.1.0"

edition = "2024"

[dependencies]
miette.workspace = true
tokio = { workspace = true, features = [ "fs" ] }
tracing.workspace = true

chrono = "0.4.43"
feed-rs = "2.3.1"
reqwest = { version = "0.13", features = [ "brotli", "zstd", "gzip", "deflate" ] }
